services:

  # --- PostGIS ---
  postgis:
    image: postgis/postgis:16-3.4
    pull_policy: never
    container_name: h-dashboard-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    # networks:
    #   - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      retries: 10

  # --- Redis ---
  redis:
    image: redis:latest
    pull_policy: never
    container_name: h-dashboard-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- pgAdmin (اختیاری ولی خیلی مفید) ---
  pgadmin:
    image: dpage/pgadmin4
    pull_policy: never
    container_name: h-dashboard-pgadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # networks:
    #   - app-network
    depends_on:
      - postgis
  # --- phpRedisAdmin ---
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    pull_policy: never
    container_name: h-dashboard-phpredisadmin
    restart: unless-stopped
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=${REDIS_PASSWORD}
    ports:
      - "8083:80"
    depends_on:
      - redis
# networks:
#   app-network:
#     driver: bridge
volumes:
  postgis_data:
  redis_data:
